import type { Metadata } from "next";
import "./globals.css";
import { Pacifico, Raleway, Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "Feedgames",
  description: "Generated by create next app",
};

const pacifico = Pacifico({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
  weight: "400",
});

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pacifico.variable} ${raleway.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
