"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.actionsRouter = void 0;
const express_1 = require("express");
const actions_controller_1 = require("../controllers/actions.controller");
exports.actionsRouter = (0, express_1.Router)();
exports.actionsRouter.get("/api/getProfile", actions_controller_1.getProfile);
exports.actionsRouter.get("/api/getProfilePosts", actions_controller_1.getProfilePosts);
exports.actionsRouter.get("/api/getPost", actions_controller_1.getPost);
exports.actionsRouter.get("/api/searchTerm", actions_controller_1.searchTerm);
exports.actionsRouter.get("/api/getFollowedById", actions_controller_1.getFollowedById);
exports.actionsRouter.get("/api/getFollowersById", actions_controller_1.getFollowersById);
