"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.commentRounter = void 0;
const express_1 = require("express");
const comment_controller_1 = require("../controllers/comment.controller");
exports.commentRounter = (0, express_1.Router)();
exports.commentRounter.post("/api/comment", comment_controller_1.comment);
exports.commentRounter.post("/api/likeComment", comment_controller_1.likeComment);
exports.commentRounter.post("/api/dontLikeComment", comment_controller_1.dontLikeComment);
exports.commentRounter.post("/api/response", comment_controller_1.response);
exports.commentRounter.get("/api/getComment", comment_controller_1.getComment);
exports.commentRounter.get("/api/getCommentsByPostId", comment_controller_1.getCommentsByPostId);
exports.commentRounter.get("/api/getResponsesByCommentId", comment_controller_1.getResponsesByCommentId);
